### ISSUE TITLE
Ensure we can use torch methods to get parameter gradients

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#10]
We will want to return the partial derivative of the models with respect to parameters at fixed state.

This requires:
1. Making sure the key objects inherit from `torch::module`
2. Register the parameter we want to take derivatives of with torch (see [here](https://pytorch.org/tutorials/advanced/cpp_frontend.html))
3. Uhh, write some tests?

**Comment by reverendbedford** [comment]
This one we may roll over to the public repo with the first release.

**Comment by hugary1995** [comment]
closed by #74
