### ISSUE TITLE
MOOSE integration

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#14]
We should have a nice interface into MOOSE, where users can construct models in a MOOSE input file and use it as if it was a native MOOSE object.

And obviously you should be able to call NEML2 models from blackbear.  Actually, I'm at the NEAMS review now and there seems to be some support to do this in `tensor_mechanics` directly.  But that's TBD.

**Comment by hugary1995** [comment]
This can be closed by https://github.com/idaholab/blackbear/pull/334

**Comment by hugary1995** [comment]
Resolved -- we decided to maintain a separate branch called `blackbear` which we will manually upgrade periodically (probably once or twice per FY) together with the blackbear submodule.
