### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by NamjaeChoi** [applied-material-modeling/neml2#143]
The example in https://reverendbedford.github.io/neml2/devel.html is showing an old `set_value` function syntax.

**Comment by hugary1995** [comment]
This is timely! I am indeed updating the entire documentation website. See PR #142 or use this link: https://reverendbedford.github.io/neml2/pr-preview/pr-142/

**Comment by hugary1995** [comment]
closed by #142

Feel free to reopen or open a new issue if some docs become outdated again. Thanks!
