### ISSUE TITLE
Create a new input file section for nonlinear parameters

### ISSUE THREAD

**Issue by hugary1995** [applied-material-modeling/neml2#150]
I am tempted to add a new input file section called something like `[NonlinearParameters]`. The advantages are:
1. Getting rid of the conceptual clash between `Model` and `NonlinearParameter` even though the latter derives from the former.
2. Easier to detect if an object is a nonlinear parameter, so that we can restrict certain API usage regarding nonlinear parameter registration.
3. Clearer documentation, as in the syntax documentation pages for `[Models]` and `[NonlinearParameters]` will be separated.

I'd explore this at some point.

**Comment by reverendbedford** [comment]
@hugary1995 has reconsidered this idea.
