### ISSUE TITLE
Add license, appropriate source file copyright statements

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#16]
Ugh, we will need to do this as well before we move things over.  I'll file a software disclosure now as it will take awhile for ANL to approve things.

**Comment by hugary1995** [comment]
I'll write a python script to do handle source file copyright headings.

The script will scan all files with specified extension names, check if there are missing/incorrect headings by comparing to a provided template.
1. The script will exit with nonzero if any change is needed.
2. Offer a command line option to let the script make the correction.

The script should also be part of the github workflow for PRs.

**Comment by hugary1995** [comment]
Once software disclosure is approved, we simply need to add the appropriate header to #40 and run the script.
