### ISSUE TITLE
state vs force

### ISSUE THREAD

**Issue by hugary1995** [applied-material-modeling/neml2#3]
I guess this is a general question which might be worth some discussion before we move too far. I feel like the current naming of "state" and "force" are reversed...

At least in my continuum mechanics class, "state" means thermodynamic variables that _completely_ pin down the system characteristics, e.g. strain -- one strain corresponds to exactly one kinematical state of the system. On the other hand, "force" is something need to be equilibriated, e.g. stress. Moreover, a force doesn't pin down the state of the system -- multiple kinematical state of the system can correspond to the same stress state (e.g. a stress-free configuration superimposed with rigid body motions).

**Comment by reverendbedford** [comment]
Extensometers don't measure strain, they measure a change in strain from some arbitrary reference point :).  That's not really state either.

I'm fine either way, but we should settle this now before we implement too many models.  I suppose I could poll some of the INL structural guys while I'm sitting here...

**Comment by hugary1995** [comment]
ya, most importantly total_strain, mechanical_strain (excluding eigenstrains), elastic_strain and inelastic_strain should all belong to the same group. I believe right now inelastic_strain is a "state" whereas total_strain is a "force".

**Comment by hugary1995** [comment]
But then there will be some complications in passing forces/state by reference, though I think that's the right thing to do.

**Comment by reverendbedford** [comment]
Yes, total_strain and inelastic_strain are in separate groups.  Mechanistically, that's because we solve for inelastic_strain but are given total_strain.  I'm not sure there is any way around that.

I guess `inputs` and `outputs` wins, so this issue is to rename everything with this notation.

**Comment by hugary1995** [comment]
closed by #28
