### ISSUE TITLE
Make sure ConstitutiveModels can be `.cuda()`

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#4]
This will be needed to run whole models on the GPU (either directly or via some manager).  When it works there will be two steps when going from CPU -> GPU.

1. Move the input data to the device.
2. Move the model to the device.

Moving `ConstutitiveModel`s will require:

1. They inherit from torch::Module.  This should be done at `StateFunction`.
2. When we create new tensors we mimic the properties of the input data.  This means we need to eliminate any references to `TorchDefaults` from the main production code.  It's fine to keep in tests.

**Comment by hugary1995** [comment]
1 should be addressed by #35.
2 still requires some work...

**Comment by hugary1995** [comment]
Closing this as notionally Models can be `.cuda()` now. I opened #68 to keep track of the TorchDefaults issue.
