### ISSUE TITLE
Rename key functional interface methods

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#5]
Right now `StateFunctions` use `value` and `dvalue` to indicate the value of the function and the derivative with respect to input.

I would like to rename these to `forward` and `D` or maybe `dforward` instead to be more compliant with libtorch.  I'm open to suggestions as well.

**Comment by reverendbedford** [comment]
If we stick with what we have we do need to alias forward to value.  I'm fine with the current names, but we'll need to this make standard torch things like pyro happy.

**Comment by hugary1995** [comment]
I think forward and value takes different input arguments. forward takes a torchTensor, value takes a LabeledVector. So we need to setup a alias regardless.

**Comment by reverendbedford** [comment]
I guess I will close this one and we'll keep the current names.
