### ISSUE TITLE
Use -DDEBUG to guard run time checks

### ISSUE THREAD

**Issue by reverendbedford** [applied-material-modeling/neml2#6]
There are several places where we check tensor sizes and names of state variables to ensure various operations are conformal.  These are good checks, but we should only apply them if we're a debug mode.

**Comment by hugary1995** [comment]
closed by #29

**Comment by hugary1995** [comment]
Reopening this as even though now we have a nice `neml_assert_dbg` method, there are still a few old-fashioned error checks scattered around.

**Comment by hugary1995** [comment]
This is closed by the first public release.
